### ISSUE TITLE
InputFile Erro

### ISSUE THREAD

**Issue by aishwaryjoshi31** [xanguera/BeamformIt#14]
When I ran the simple way using do_beamforming.sh to obtain tdoa feature, I am getting Input File error @ #
![screenshot from 2017-04-18 16-37-02](https://cloud.githubusercontent.com/assets/20510586/25127138/6ed46c78-2452-11e7-8da8-2d90259a5a9b.png)

**Comment by xanguera** [comment]
Your path is not correct. It assumes /is1002b/...
Check your paths to make sure you pass it full path til that point, instead
of relative.


On Apr 18, 2017 12:47 PM, "aishwaryjoshi31" <notifications@github.com>
wrote:

When I ran the simple way using do_beamforming.sh to obtain tdoa feature, I
am getting Input File error @ #
[image: screenshot from 2017-04-18 16-37-02]
<https://cloud.githubusercontent.com/assets/20510586/25127138/6ed46c78-2452-11e7-8da8-2d90259a5a9b.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xanguera/BeamformIt/issues/14>, or mute the thread

**Comment by xanguera** [comment]
Closing as I suspect the user already solved the issue.
