### ISSUE TITLE
question about real-time performance

### ISSUE THREAD

**Issue by jingxuan9862** [xanguera/BeamformIt#17]
Hi , when I use the BeamformIt to process my rocodings ,it preforms well ,but there is a doubt that can the BeamformIt work realtime?

**Comment by xanguera** [comment]
Hi,
I suspect you mean "online",right?
IT currently does not work online because it performs some postprocessing
to the TDOA values to improve them. If you refactored the code and ignored
this postprocessing and some preprocessing it could run online.

**Comment by jingxuan9862** [comment]
ok ,thank you.

**Comment by kukzile** [comment]
The compilation takes about 15 seconds. Can that be reduced if we want to use this in real time? 
By real time i mean,recording data, then processing it (beamform) and passing it to speech recognition algorithm.

**Comment by xanguera** [comment]
I am sure you could. The original code was not coded for speed, but as a
research project.
One quick thing you could do is disable the postprocessing of TDOA delays,
but this will deteriorate a bit the results...

**Comment by dyustc** [comment]
Hi, I am also consider using it in real-time, there is one small issue bothering me, I saw the default setting of scroll(shift) length of audio is 250ms, or the window length is 500ms, is this a lot to bear as for real time communication? I am wondering if a much smaller shift could be put to use and still have a decent beamforming effect.

**Comment by xanguera** [comment]
Yes, you can try with smaller window and shift. The performance might
degrade though.

**Comment by dyustc** [comment]
Thanks for the quick reply.  I tested it with a window length of 20ms, and scroll length of 10ms, much smaller than the default ones, there is a little bit degradation, but not much. 

But I also found that if the reference channel number is calculated adaptively instead of using the whole picture, the performance is degraded more.  Anyway, I am thinking using this beamformer as a frontend for a more solid denoised output of a neural network. Currently with the default setting, it works fine.  Maybe as I change the setting more, there will be more findings.

**Comment by xanguera** [comment]
If you know which channel should be the best, then skip the reference
channel calculation. I believe there was an option for that.
I agree that with such small window you will not have enough info to select
a good reference adaptively.
Another solution (if you do not know the best channel a priori) would be ro
tely a lot more on the history so that the reference channel stabilizes
over time (i.e. it does not use so much of the current info, but more of
the aggregate prior). There is nothing there that does that, you would need
to built it.

Xavier
